### ISSUE TITLE
encourage users to pull template via `wasp new` 

### ISSUE THREAD

**Issue by vincanger** [wasp-lang/open-saas#87]
- [ ] remove the `Use This Template` feature on this GitHub repo
- [ ] remove mentions of `Use This Template` in the docs
- [ ] add instructions on using `wasp new -t saas` to docs

**Comment by Martinsos** [comment]
We can discuss this more @vincanger , to make sure it is the right move -> it does feel like the right direction to me at the moment, because I think it gives us needed flexibility to both provide best experience for developing open-saas and also best experience for using it, but if you think we are loosing something, I would love to take that into account.

**Comment by vincanger** [comment]
@Martinsos I think youre right, that the easiest path to a clean install is via `wasp new` so i've updated the docs to inform users to pull the template that way :)

**Comment by Martinsos** [comment]
> @Martinsos I think youre right, that the easiest path to a clean install is via `wasp new` so i've updated the docs to inform users to pull the template that way :)

Ok! But we still have the option to make a template out of the repo, what about that?
Also, once we made the decision to do it via `wasp new`, we can immediately put a bit of work into utilizing that, in the sense that we can remove some redundant files and similar. I would at least make a task for that.
